name: GitHub SSH Action Test
run-name: ${{ github.actor }} is testing out GitHub Actions ðŸš€
on:
  push
jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
      - run: which rsync
      - run: echo "HI ${{ vars.NAME }}"
      - run: echo "ðŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ðŸ”Ž The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: sha256sum README.md
      - run: echo "ðŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ðŸ–¥ï¸ Thee workflow is now ready to test your code on the runner."
      - name: 'List files in the repository'
        run: |
          ls ${{ github.workspace }}
      - run: echo "ðŸ This job's status is ${{ job.status }}."
      - name: Write deployment key/ident to a file
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.HOST_KEY }}" >> ~/.ssh/known_hosts
          echo "${{ secrets.SSH_DEPLOYMENT_KEY }}" > ./sshtest.priv
          chmod 600 ./sshtest.priv
      - name: Copy readme to external server
        run: scp -i ./sshtest.priv "${{ github.workspace }}/README.md" "${{ secrets.USER }}@${{ secrets.HOST }}:"
      - name: Run incoming queue rsync command
        run: ssh -i ./sshtest.priv "${{ secrets.User }}@${{ secrets.HOST }}" "date"
